# my_project/config.py

MODEL:
    MODEL_LIBRARY: 'timm'
    MODEL_NAME: 'efficientnet_b5'
DIRS:
    ROOT_DIR: '/home/edmorris/projects/image_classification/caltech_birds'
TRAIN:
    NUM_EPOCHS: 200
    SCHEDULER:
        TYPE: 'ReduceLROnPlateau'
        PARAMS: ['metric_name', 'loss','mode', 'min', 'factor', 0.1, 'patience', 10, 'threshold', 0.0001, 'threshold_mode', 'rel', 'cooldown', 0, 'min_lr', 0.00001, 'eps', 1e-08]
DATA: 
    TRANSFORMS:
        PARAMS:
            DEFAULT:
                img_crop_size: 456
                img_resize: 512