# my_project/config.py

MODEL:
    MODEL_LIBRARY: 'timm'
    MODEL_NAME: 'efficientnet_em'
DIRS:
    ROOT_DIR: '/home/edmorris/projects/image_classification/caltech_birds'
TRAIN:
    NUM_EPOCHS: 40
DATA: 
    TRANSFORMS:
        PARAMS:
            DEFAULT:
                img_crop_size: 240
                img_resize: 256