# my_project/config.py

MODEL:
    MODEL_LIBRARY: 'pytorchcv'
    MODEL_NAME: 'efficientnet_b0'
DIRS:
    ROOT_DIR: '/home/edmorris/projects/image_classification/caltech_birds'
TRAIN:
    NUM_EPOCHS: 40